server {
    listen       80;
    # ドメイン名の指定
    server_name  localhost:80;

    location /next/ {
        resolver 127.0.0.11 valid=5s;
        set $newFrontend "next";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/next/(.*)$ /$1 break;
        proxy_pass http://$newFrontend:3000;
    }

    location /_next/ {
        resolver 127.0.0.11 valid=5s;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        set $newFrontend "next";
        proxy_pass http://$newFrontend:3000;
    }

    location /nuxt/ {
        # 5s ごとに参照し，初期段階で nuxt が立ち上がっていなくてもエラーにならなくなる
        resolver 127.0.0.11 valid=5s;
        set $frontend "nuxt";

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        rewrite ^/nuxt/(.*)$ /$1 break;
        proxy_pass http://$frontend:3000;
    }

    location /_nuxt/ {
        resolver 127.0.0.11 valid=5s;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        set $frontend "nuxt";
        # _nuxt へはそのままリクエストだしたいから rewrite 不要
        proxy_pass http://$frontend:3000;
    }

    location /api/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://go:8080;
    }

    # エラーコードが発生した際に表示するURIの指定
    error_page   500 502 503 504  /50x.html;
    # "/50x.html"ページへ内部リダイレクト
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}

